image: containers.cisco.com/cway/gitlab-ci:3.4.1

stages:
  - static
  # - automation
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

# disable gitlab cli analytics
before_script:
  - export NG_CLI_ANALYTICS=false
  - npm ci --audit=false

building:
  stage: build
  only:
    - merge_requests
  script:
    - npm run build:ci

# run npm audit to verify dependency security
audit:
  stage: build
  allow_failure: true # temporary until @compodoc fixes their vulnerability issue, since this is only used for document generation, I dont consider it breaking
  only:
    - merge_requests
  script:
    - npm audit

# run our lint process against the committed files
lint:
  stage: static
  only:
    - merge_requests
  script:
    - npm run lint
    - npm run lint:cypress
    - npm run lint:sdp

#commit linting:
  #stage: static
  # only on merge requests cannot be removed here or else the target branch will be incorrect
  #only:
  #  - merge_requests
  #script:
  #  - npm run lint:commit:message

# run our test:ci process for the commit
unit:
  stage: static
  only:
    - merge_requests
  script:
    - npm run test:ci

# run automated Cypress tests for the commit
# .job_template: &cypress_spec
#   stage: automation
#   cache:
#     key: "PIPELINE-$CI_PIPELINE_ID"
#     policy: pull
#     paths:
#       - package-lock.json
#       - node_modules/
#   allow_failure: true
#   before_script:
#     - npm run start:background
#     - cp "cypress/patches/verify.js" "node_modules/cypress/lib/tasks"
#   script:
#     - npm run test:automation -- --spec "cypress/integration/$CI_BUILD_NAME.js"

# Stable cypress specs to be run in CI
# TODO: Add more spec files once they are stable
# accelerator_spec:
#   <<: *cypress_spec
# advisories_spec:
#   <<: *cypress_spec
# assets_spec:
#   <<: *cypress_spec
# atx_spec:
#   <<: *cypress_spec
# casedetail_spec:
#   <<: *cypress_spec
# communities_spec:
#   <<: *cypress_spec
# insights_spec:
#   <<: *cypress_spec
# learning_spec:
#   <<: *cypress_spec
# settings_spec:
#   <<: *cypress_spec
