image: containers.cisco.com/cway/gitlab-ci:3.4.0

stages:
  - setup
  - test
  - build

# add 'node_modules' to cache for speeding up builds
cache:
  key: "PIPELINE-$CI_PIPELINE_ID"
  paths:
    - node_modules/ # Node modules and dependencies

# disable gitlab cli analytics
before_script:
  - export NG_CLI_ANALYTICS=false

setup:
  stage: setup
  script:
    - npm install --audit=false
    - rm -rf node_modules/@types/lodash

building:
  stage: build
  script:
    - npm run build:ci

# run npm audit to verify dependency security
audit:
  stage: setup
  allow_failure: true # temporary until @compodoc fixes their vulnerability issue, since this is only used for document generation, I dont consider it breaking
  before_script:
    - npm install --package-lock=true --package-lock-only
  script:
    - npm audit

# run our lint process against the committed files
lint:
  stage: test
  script:
    - npm run lint
    - npm run lint:cypress

# run our test:ci process for the commit
unit:
  stage: test
  script:
    - npm run test:ci

# run our test:automation process for the commit
automation:
  stage: test
  only:
    - master
  before_script:
    - npm run start:background
  script:
    - CYPRESS_CI=$CI CYPRESS_CI_JOB_URL=$CI_JOB_URL CYPRESS_REPORT_URL=https://swtg-qa-apollo-2.cisco.com/ws/cypress-reporting/v1/report npm run test:automation
