# temporary until we find another suitable image
image: blakecallens/nodejs-chromium

stages:
  - setup
  - audit
  - lint
  - test

# add 'node_modules' to cache for speeding up builds
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths: 
    - node_modules/ # Node modules and dependencies

setup:
  stage: setup
  script:
    - npm install --package-lock=true --audit=false

# run npm audit to verify depdency security
audit:
  stage: audit
  allow_failure: true # temporary until @compodoc fixes their vulnerability issue, since this is only used for document generation, I dont consider it breaking
  script:
    - npm audit

# run our lint process against the committed files
lint:
  stage: lint
  script:
    - npm run lint

# run our test:ci process for the commit
unit:
  stage: test
  script:
    - npm run test:ci

# run our test:automation process for the commit
automation:
  stage: test
  before_script:
    - apt-get update && apt-get -y install xvfb libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2
    - npx cypress install
  script:
    - npm run test:automation