export { VulnerabilityResponse } from './models/vulnerability-response';
export { ErrorResponse as ProductAlertsErrorResponse } from './models/error-response';
export { SecurityAdvisoryResponse } from './models/security-advisory-response';
export { SecurityAdvisory } from './models/security-advisory';
export { SecurityAdvisoryBulletinResponse } from './models/security-advisory-bulletin-response';
export { SecurityAdvisoryBulletin } from './models/security-advisory-bulletin';
export { FieldNoticeResponse } from './models/field-notice-response';
export { FieldNotice } from './models/field-notice';
export { FieldNoticeBulletinResponse } from './models/field-notice-bulletin-response';
export { FieldNoticeBulletin } from './models/field-notice-bulletin';
export { Pagination as ProductAlertsPagination } from './models/pagination';
export { HardwareEOLResponse } from './models/hardware-eolresponse';
export { HardwareEOL } from './models/hardware-eol';
export { HardwareEOLBulletinResponse } from './models/hardware-eolbulletin-response';
export { HardwareEOLBulletin } from './models/hardware-eolbulletin';
export { HardwareEOLCountResponse } from './models/hardware-eolcount-response';
export { SoftwareEOLResponse } from './models/software-eolresponse';
export { SoftwareEOL } from './models/software-eol';
export { SofwareEOLBulletinResponse } from './models/sofware-eolbulletin-response';
export { SoftwareEOLBulletin } from './models/software-eolbulletin';
export { SecurityAdvisorySummary } from './models/security-advisory-summary';
