/* tslint:disable */
export { VulnerabilityResponse } from './models/vulnerability-response';
export { ErrorResponse as ProductAlertsErrorResponse } from './models/error-response';
export { SecurityAdvisoryResponse } from './models/security-advisory-response';
export { SecurityAdvisoriesResponse } from './models/security-advisories-response';
export { SecurityAdvisoryInfo } from './models/security-advisory-info';
export { SecurityAdvisory } from './models/security-advisory';
export { SecurityAdvisoryBulletinResponse } from './models/security-advisory-bulletin-response';
export { SecurityAdvisoryBulletin } from './models/security-advisory-bulletin';
export { SecurityAdvisoryImpactCountResponse } from './models/security-advisory-impact-count-response';
export { SecurityAdvisoryImpactedInfoAndCount } from './models/security-advisory-impacted-info-and-count';
export { FieldNoticeResponse } from './models/field-notice-response';
export { FieldNotice } from './models/field-notice';
export { FieldNoticeBulletinResponse } from './models/field-notice-bulletin-response';
export { FieldNoticeBulletin } from './models/field-notice-bulletin';
export { FieldNoticeAdvisoryResponse } from './models/field-notice-advisory-response';
export { FieldNoticeAdvisory } from './models/field-notice-advisory';
export { FieldNoticeUpdatedResponse } from './models/field-notice-updated-response';
export { Pagination as ProductAlertsPagination } from './models/pagination';
export { HardwareEOLResponse } from './models/hardware-eolresponse';
export { HardwareEOL } from './models/hardware-eol';
export { HardwareEOLBulletinResponse } from './models/hardware-eolbulletin-response';
export { HardwareEOLBulletin } from './models/hardware-eolbulletin';
export { HardwareEOLCountResponse } from './models/hardware-eolcount-response';
export { SoftwareEOLResponse } from './models/software-eolresponse';
export { SoftwareEOL } from './models/software-eol';
export { SoftwareEOLBulletinResponse } from './models/software-eolbulletin-response';
export { SoftwareEOLBulletin } from './models/software-eolbulletin';
export { SecurityAdvisorySummary } from './models/security-advisory-summary';
export { SecurityAdvisorySeverityCountResponse } from './models/security-advisory-severity-count-response';
export { AdvisoriesByLastUpdatedCount } from './models/advisories-by-last-updated-count';
export { LastUpdatedCount } from './models/last-updated-count';
