swagger: '2.0'
info:
  description: CDX API Services
  version: v1
  title: API Services
  termsOfService: ''
  contact:
    email: vpriyata@cisco.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: '4carmn1vef.execute-api.us-east-2.amazonaws.com'
basePath: '/cluster2-dev'
security:
  - OauthSecurity: []
schemes:
  - https
paths:
  /api/customerportal/v1/party/accounts:
    get:
      tags:
        - Organization
      summary: Returns all accounts including virtual accounts associate to this customer.
      description: Returns all accounts including virtual accounts associate to this customer.
      operationId: getAccounts
      produces:
        - application/json
      parameters:
        - name: customerId
          in: query
          description: Unique identifier of a Cisco customer.
          required: true
          type: string
        - name: sort
          in: query
          description: Supported sort criteria are either ‘asc’ for ascending or ‘desc’ for descending.
          required: false
          type: array
          items:
            type: string
          collectionFormat: multi
        - name: fields
          in: query
          description: Requested fields in the response.
          required: false
          type: array
          items:
            type: string
          collectionFormat: csv
        - name: page
          in: query
          description: Page number of the response
          required: false
          type: integer
          format: int32
          minimum: 1
        - name: rows
          in: query
          description: Number of rows of data per page.
          required: false
          type: integer
          format: int64
          minimum: 1
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/ResponseObject'
        500:
          description: '500 response'
        401:
          description: '401 response'
        403:
          description: '403 response'
securityDefinitions:
  OauthSecurity:
    type: oauth2
    flow: implicit
    authorizationUrl: 'https://oauth.simple.api/authorization'
definitions:
  ResponseObject:
    type: object
    required:
      - data
    properties:
      data:
        type: array
        items:
          $ref: '#/definitions/ResponseObjectDetails'

  ResponseObjectDetails:
    type: object
    properties:
      customerId:
        type: string
        description: This is the party identifier used throught the system. This can be a CR Party Id, Smart Account, Virtual Account
      genId:
        type: string
        description: This is the party identifier assigned by the profiling system  
      domainName:
        type: string
        description: The domain name under which the Smart Account is registered
      smartAccount:
        type: array
        items:
          type: object
          properties:
            smartAccountId:
              type: string
              description: This is an internal identifier (Smart Account)
            smartAccountName:
              type: string
              description: The textual name for the Smart Account
            userList:
              type: array
              items:
                type: string
            tags:
              type: array
              items:
                type: object
                properties:
                  tagName:
                    type: string
                    description: Tag Name
                  tagValue:
                    type: string
                    description: Tag Value
            virtualAccount:
              type: array
              items:
                type: object
                properties:
                  virtualAccountId:
                    type: string
                    description: The VirtualAccount Id. This is an internal identifier (Smart Account)
                  virtualAccountName:
                    type: string
                    description: The textual name of the Virtual Account
                  userList:
                    type: array
                    items:
                      type: string
      subscribedService:
        type: string
        description: The service to which the customer is subscribed. This is the service identifier from the contract
      serviceLevel:
        type: string
        description: The service level (e.g. L1, L2)