module.exports = {
	extends: 'tslint-config-airbnb',
	defaultSeverity: 'error',
	rules: {
		// OFF
		'function-name': false,
		'import-blacklist': false,
		'no-unsafe-any': false,

		// WARNINGS
		'adjacent-overload-signatures': {
			severity: 'warning',
		},
		eofline: {
			severity: 'warning',
		},
		forin: {
			severity: 'warning',
		},
		'object-literal-sort-keys': {
			severity: 'warning',
			options: [
				'ignore-case',
				'shorthand-first',
			],
		},
		'newline-before-return': {
			severity: 'warning',
		},
		'no-any': {
			severity: 'warning',
		},
		radix: {
			severity: 'warning',
		},
		ban: {
			severity: 'warning',
			options: [
				{
					name: 'setTimeout',
					message: 'Please consider if this is a necessary function and not to force change detection',
				},
				{
					name: ['*', 'toPromise'],
					message: 'Please consider using observables when possible',
				},
			],
		},

		// ERRORS
		align: true,
		'arrow-return-shorthand': [true, 'multiline'],
		'ban-comma-operator': true,
		'ban-ts-ignore': true,
		'callable-types': true,
		'class-name': true,
		'comment-format': [true, 'check-space'],
		'completed-docs': [
			true,
			'classes',
			'functions',
			'interfaces',
			'methods',
			'namespaces',
			'types',
			'variables',
		],
		curly: true,
		'import-spacing': true,
		indent: [true, 'tabs', 4],
		'interface-over-type-literal': true,
		'jsdoc-format': true,
		'label-position': true,
		'member-access': true,
		'member-ordering': [
			true,
			{
				order: [
					'static-field',
					'instance-field',
					'static-method',
					'instance-method',
				],
			},
		],
		'newline-per-chained-call': true,
		'no-empty': true,
		'no-string-literal': true,
		'no-arg': true,
		'no-as-type-assertion': true,
		'no-bitwise': true,
		'no-collapsible-if': true,
		'no-console': true,
		'no-construct': true,
		'no-debugger': true,
		'no-duplicate-super': true,
		'no-empty-interface': true,
		'no-eval': true,
		'no-inferrable-types': [true, 'ignore-params'],
		'no-irregular-whitespace': true,
		'no-misused-new': true,
		'no-non-null-assertion': true,
		'no-parameter-reassignment': true,
		'no-return-undefined': true,
		'no-shadowed-variable': true,
		'no-string-throw': true,
		'no-switch-case-fall-through': true,
		'no-trailing-whitespace': true,
		'no-unnecessary-else': true,
		'no-unnecessary-initializer': true,
		'no-unused-expression': true,
		'no-unused': true,
		'no-use-before-declare': true,
		'no-var-before-return': true,
		'no-var-keyword': true,
		'object-literal-shorthand': true,
		'object-shorthand-properties-first': true,
		'one-line': [
			true,
			'check-open-brace',
			'check-catch',
			'check-else',
			'check-whitespace',
		],
		'prefer-const': true,
		'prefer-template': true,
		quotemark: [
			true,
			'single',
			'avoid-escape',
			'avoid-template',
		],
		semicolon: [true, 'always'],
		'space-before-function-paren': true,
		'ter-arrow-body-style': [true, 'as-needed'],
		'ter-arrow-parens': [true, 'as-needed'],
		'ter-indent': [
			true,
			'tab',
			{
				SwitchCase: 1,
			},
		],
		'ter-max-len': [
			true,
			{
				code: 100,
				comments: 100,
				ignoreImports: true,
				ignoreUrls: true,
				ignoreRegExpLiterals: true,
			},
		],
		'trailing-comma': [
			true,
			{
				multiline: 'always',
				singleline: 'never',
			},
		],
		'triple-equals': true,
		'typedef-whitespace': [
			true,
			{
				'call-signature': 'nospace',
				'index-signature': 'nospace',
				'property-declaration': 'nospace',
				'variable-declaration': 'nospace',
				parameter: 'nospace',
			},
			{
				'call-signature': 'onespace',
				'index-signature': 'onespace',
				parameter: 'onespace',
				'property-declaration': 'onespace',
				'variable-declaration': 'onespace',
			},
		],
		'unified-signatures': true,
		'valid-jsdoc': [
			true,
			{
				prefer: {
					return: 'returns',
				},
				requireParamDescription: true,
				requireParamType: false,
				requireReturn: false,
				requireReturnDescription: true,
				requireReturnType: false,
			},
		],
		'valid-typeof': true,
		'variable-name': [true, 'ban-keywords'],
		whitespace: [
			true,
			'check-branch',
			'check-decl',
			'check-operator',
			'check-module',
			'check-separator',
			'check-rest-spread',
			'check-type',
			'check-typecast',
			'check-type-operator',
			'check-preblock',
			'check-postbrace',
		],
	},
};
